use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};

/// Trading direction.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Direction {
    Long,
    Short,
}

impl Direction {
    pub fn opposite(&self) -> Self {
        match self {
            Direction::Long => Direction::Short,
            Direction::Short => Direction::Long,
        }
    }

    pub fn is_buy(&self) -> bool {
        matches!(self, Direction::Long)
    }
}

/// A trading signal generated by a strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    pub coin: String,
    pub direction: Direction,
    pub direction_score: f64,
    pub entry_price: f64,
    pub stop_loss: f64,
    pub take_profit: f64,
    pub timestamp: i64,
}

/// Intent emitted by the strategy — never talks directly to the exchange.
#[derive(Debug, Clone)]
pub enum Intent {
    /// No action.
    NoTrade,

    /// Place a passive (ALO) entry order.
    /// `size` starts at ZERO — main.rs computes it via RiskManager before execution.
    PlacePassiveEntry {
        coin: String,
        direction: Direction,
        price: Decimal,
        /// Stop-loss price — used by risk manager to compute position size.
        stop_loss: Decimal,
        /// Take-profit price — placed as trigger order after fill.
        take_profit: Decimal,
        size: Decimal,
        max_wait_s: u64,
    },

    /// Amend an existing passive entry order (preserves queue position).
    AmendPassiveEntry {
        oid: String,
        new_price: Decimal,
    },

    /// Cancel an entry order.
    CancelEntry {
        oid: String,
        reason: String,
    },

    /// Place a passive (GTC) exit order.
    PlacePassiveExit {
        coin: String,
        /// Position direction being closed — exit order is the opposite side.
        direction: Direction,
        price: Decimal,
        size: Decimal,
    },

    /// Force exit via IOC (regime-forced, timeout, circuit breaker).
    ForceExitIoc {
        coin: String,
        /// Position direction being closed — exit order is the opposite side.
        direction: Direction,
        /// Current mid — used as IOC limit with slippage headroom.
        mid_price: Decimal,
        size: Decimal,
        reason: String,
    },

    /// Reduce position size.
    ReducePosition {
        coin: String,
        size: Decimal,
    },

    /// Enter cooldown for a coin.
    Cooldown {
        coin: String,
        duration_s: u64,
    },
}
